version: '3.4'

services:

  productdb:
    container_name: productdb
    environment: 
      - POSTGRES_USER=darvyxe
      - POSTGRES_PASSWORD=125451254mS
      - POSTGRES_DB=ProductDb
    restart: always
    ports: 
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgrsql/data/
  pgadmin:
    container_name: pgadmin
    environment: 
      - PGADMIN_DEFAULT_EMAIL=darvyxe@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=125451254mS
    restart: always
    ports:
      - "5070:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
  products.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "10000:8080"
    depends_on:
      - productdb
