// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Products.Infrastructure;

#nullable disable

namespace Products.Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20240530203935_init-db")]
    partial class initdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Products.Domain.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("BannerUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://placehold.co/500x100.png");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2024, 5, 30, 20, 39, 33, 951, DateTimeKind.Utc).AddTicks(120));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://placehold.co/85.png");

                    b.Property<DateTime>("ModificationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2024, 5, 30, 20, 39, 33, 951, DateTimeKind.Utc).AddTicks(414));

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Permalink")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://placehold.co/150.png");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 182,
                            Active = true,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Minim occaecat eu ea anim excepteur qui. Voluptate adipisicing sunt in enim deserunt labore esse ut non occaecat anim elit. Cillum laborum nostrud veniam magna do.\r\n",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Olga-Guthrie",
                            Priority = 0,
                            Title = "Maryanne Clements"
                        },
                        new
                        {
                            Id = 168,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cupidatat ea ut cupidatat aliquip id enim irure cillum reprehenderit magna. Voluptate dolor cupidatat deserunt sint ipsum aliqua sint ut pariatur cupidatat anim. Mollit cupidatat sit do nisi ad amet labore velit minim officia officia ad in id. Ut nulla aute nulla dolor.\r\n",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Beverly-Fitzpatrick",
                            Priority = 0,
                            Title = "Ware Daugherty"
                        },
                        new
                        {
                            Id = 66,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dolore dolor pariatur magna ad esse. Enim nisi consectetur duis duis aute mollit Lorem culpa. Irure excepteur voluptate do enim aliqua nisi. Et irure enim fugiat tempor culpa ad proident nisi nulla exercitation irure ipsum irure in.\r\n",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Clarke-Hammond",
                            Priority = 0,
                            Title = "Jodie Baxter"
                        },
                        new
                        {
                            Id = 175,
                            Active = true,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorem cupidatat id ea aute et voluptate consequat quis. Irure cillum aute veniam sit exercitation ex Lorem ex eu fugiat aliqua non incididunt qui. Non mollit culpa velit eiusmod commodo anim proident laborum voluptate ipsum. Dolor voluptate consectetur sint culpa esse nostrud quis amet. Mollit eiusmod ex deserunt consectetur tempor dolore eiusmod cillum occaecat.\r\n",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Terry-May",
                            Priority = 0,
                            Title = "Janet Pacheco"
                        },
                        new
                        {
                            Id = 155,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nisi quis enim proident duis mollit exercitation eiusmod reprehenderit. Ex ex deserunt laboris esse commodo commodo. Ut officia est tempor incididunt qui eu laborum elit mollit eu irure veniam. Aute reprehenderit occaecat labore elit ullamco. Nulla deserunt aliqua esse culpa velit sit elit et nostrud labore dolore. Pariatur qui consectetur deserunt eu officia est magna in amet ea qui. Cillum labore proident ipsum in sunt exercitation veniam ipsum sit.\r\n",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Rosemary-Burnett",
                            Priority = 0,
                            Title = "Pacheco Vega"
                        },
                        new
                        {
                            Id = 67,
                            Active = true,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Exercitation ad exercitation consequat quis Lorem aute. Veniam ut irure irure est Lorem Lorem ullamco voluptate tempor. Labore eiusmod officia sint cupidatat eiusmod voluptate anim culpa amet quis adipisicing do ipsum. Cillum cupidatat in sunt enim consequat. Officia cupidatat est deserunt enim sunt. Dolore laborum consequat est incididunt incididunt eiusmod nostrud. Et sint sunt esse incididunt eu dolore velit enim voluptate qui ut.\r\n",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Turner-Henry",
                            Priority = 0,
                            Title = "Jacqueline Kidd"
                        },
                        new
                        {
                            Id = 89,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Proident deserunt nisi esse eu commodo ea incididunt aliqua. Id id amet id adipisicing voluptate. Est duis non nisi laboris tempor.\r\n",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Myra-Francis",
                            Priority = 0,
                            Title = "Mara Wade"
                        },
                        new
                        {
                            Id = 124,
                            Active = true,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ut ipsum veniam sint et do id pariatur duis. Commodo officia velit duis fugiat sint deserunt officia duis proident quis. Eu quis sunt Lorem reprehenderit quis ea pariatur tempor fugiat dolor incididunt. Est enim tempor irure non dolore proident culpa laborum. Anim exercitation sunt proident eu occaecat cupidatat. Incididunt nisi amet id ea qui amet magna qui fugiat. Laborum sit qui ea exercitation reprehenderit.\r\n",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Bettye-Gregory",
                            Priority = 0,
                            Title = "Jan Delgado"
                        });
                });

            modelBuilder.Entity("Products.Domain.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://placehold.co/150.png");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2024, 5, 30, 20, 39, 33, 950, DateTimeKind.Utc).AddTicks(7917));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("ModificationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2024, 5, 30, 20, 39, 33, 950, DateTimeKind.Utc).AddTicks(8265));

                    b.Property<string>("Permalink")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Products.Domain.Categories.Category", b =>
                {
                    b.HasOne("Products.Domain.Categories.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Products.Domain.Products.Product", b =>
                {
                    b.HasOne("Products.Domain.Categories.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Products.Domain.Categories.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
